// ─── GETSE Web Localization ────────────────────────────────────────────────────
// Supports English (en) and Amharic (am)

export const translations = {
  en: {
    // Navbar
    catalog: 'Catalog',
    my_library: 'My Library',
    publish: 'Publish',
    revenue: 'Revenue',
    ai_writer: 'AI Writer',
    admin: 'Admin',
    login_register: 'Login / Register',
    logout: 'Logout',

    // Home page
    hero_title: "Ethiopia's Digital Library",
    hero_desc: 'Discover, purchase, and read thousands of Amharic and English books — from your favorite Ethiopian authors.',
    browse_catalog: 'Browse Catalog',
    get_started: 'Get Started',
    books_available: 'Books Available',
    authors_readers: 'Ethiopian Authors & Readers',
    purchases_made: 'Purchases Made',
    languages_supported: 'Languages Supported',

    // Auth
    welcome_back: 'Welcome Back',
    create_account: 'Create Account',
    signin_prompt: 'Sign in to your GETSE account',
    join_prompt: 'Join thousands of Ethiopian readers & authors',
    username: 'Username',
    role_prompt: 'I am a...',
    reader: 'Reader',
    author: 'Author',
    email: 'Email',
    password: 'Password',
    please_wait: 'Please wait...',
    login: 'Login',
    register: 'Register',
    no_account: "Don't have an account?",
    has_account: 'Already have an account?',
    demo_accounts: 'Demo Accounts',

    // Catalog
    catalog_title: 'Book Catalog',
    search_books: 'Search books...',
    all_languages: 'All Languages',
    english: 'English',
    amharic: 'Amharic',
    no_books_found: 'No books found.',
    purchase: 'Purchase',
    read_now: 'Read Now',
    purchased: 'Purchased ✓',
    birr: 'ETB',

    // Library
    my_library_title: 'My Library',
    my_books: 'My Books',
    recommendations: 'Recommendations',
    no_books_yet: 'No books in your library yet.',
    browse_catalog_cta: 'Browse the catalog to find something you love!',
    no_recommendations: 'No recommendations yet.',
    purchase_more: 'Purchase more books to unlock personalized suggestions!',
    download_pdf: 'Download PDF',

    // Publish
    publish_book: 'Publish a Book',
    book_title: 'Book Title',
    description: 'Description',
    price_birr: 'Price (ETB)',
    language: 'Language',
    cover_url: 'Cover Image URL',
    pdf_url: 'PDF URL',
    publish_btn: 'Publish Book',
    publishing: 'Publishing...',
    my_publications: 'My Publications',
    no_publications: 'No books published yet.',

    // Revenue
    revenue_title: 'Revenue Dashboard',
    total_revenue: 'Total Revenue',
    total_sales: 'Total Sales',
    avg_price: 'Avg. Price',
    recent_sales: 'Recent Sales',
    no_sales: 'No sales yet.',
    book: 'Book',
    buyer: 'Buyer',
    amount: 'Amount',
    date: 'Date',

    // Admin
    admin_panel: 'Admin Panel',
    total_books: 'Total Books',
    total_users: 'Total Users',
    total_purchases: 'Total Purchases',
    manage_books: 'Manage Books',
    title_author: 'Title / Author',
    actions: 'Actions',
    delete: 'Delete',

    // AI Assistant
    ai_assistant: 'AI Writing Assistant',
    ai_desc: 'Get AI-powered feedback on your writing to improve quality and engagement.',
    paste_text: 'Paste your text for analysis:',
    analyze: 'Analyze with AI →',
    analyzing: 'Analyzing...',
    ai_feedback: 'AI Feedback',
    suggestions: '💡 Suggestions',
    submit_for_feedback: 'Submit your text to get AI-powered writing feedback',
    ai_analyzing: 'AI is analyzing your text...',

    // Payment
    purchase_book: 'Purchase Book',
    select_payment: 'Select Payment Method',
    phone_number: 'Phone Number / Account',
    pay_now: 'Pay Now',
    processing: 'Processing...',
    payment_success: '✅ Payment Successful!',
    continue_reading: 'Continue Reading',
    cancel: 'Cancel',

    // Missing Keys
    publish_subtitle: 'Share your work with Ethiopian readers worldwide',
    library_subtitle: 'Your purchased books — read online or on the GETSE mobile app',
    purchased_on: 'Purchased:',
    view_in_catalog: 'View in Catalog',
    revenue_subtitle: 'Track your book sales and income',
    no_sales_yet: 'No sales yet. Publish books and start earning!',
    sold: 'sold',
    user_management: 'User Management',
    refresh: '↻ Refresh',
    no_users_found: 'No users found',
    remove: 'Remove',
    ai_subtitle: 'Powered by intelligent NLP — get instant feedback, vocabulary suggestions, and cover design concepts for your book',
    analysis_type: 'Analysis Type',
    oromia: 'Oromia',
    tigrinya: 'Tigrinya',
    by: 'by',
    login_to_purchase: 'Login to Purchase',
    patent_url: 'Patent / Copyright Document URL (PDF/Image)',
  },

  am: {
    // Navbar
    catalog: 'ካታሎግ',
    my_library: 'የእኔ ቤተ-መጽሐፍት',
    publish: 'ያሳትሙ',
    revenue: 'ገቢ',
    ai_writer: 'የ AI ጸሐፊ',
    admin: 'አስተዳዳሪ',
    login_register: 'ይግቡ / ይመዝገቡ',
    logout: 'ይውጡ',

    // Home page
    hero_title: 'የኢትዮጵያ ዲጂታል ቤተ-መጻሕፍት',
    hero_desc: 'በሺዎች የሚቆጠሩ የአማርኛ እና የእንግሊዝኛ መጻሕፍትን ከሚወዷቸው ኢትዮጵያውያን ደራሲዎች ያግኙ፣ ይግዙ እንዲሁም ያንብቡ።',
    browse_catalog: 'ካታሎጉን ያስሱ',
    get_started: 'አሁኑኑ ይጀምሩ',
    books_available: 'የሚገኙ መጻሕፍት',
    authors_readers: 'ኢትዮጵያውያን ደራሲዎች እና አንባቢዎች',
    purchases_made: 'የተፈጸሙ ግዢዎች',
    languages_supported: 'የሚደገፉ ቋንቋዎች',

    // Auth
    welcome_back: 'እንኳን ደህና መጡ',
    create_account: 'አዲስ መለያ ይፍጠሩ',
    signin_prompt: 'ወደ መለያዎ ይግቡ',
    join_prompt: 'በሺዎች የሚቆጠሩ ኢትዮጵያውያን አንባቢዎችን እና ደራሲዎችን ይቀላቀሉ',
    username: 'የተጠቃሚ ስም',
    role_prompt: 'የእኔ ሚና...',
    reader: 'አንባቢ',
    author: 'ደራሲ',
    email: 'ኢሜይል',
    password: 'የይለፍ ቃል',
    please_wait: 'እባክዎ ይጠብቁ...',
    login: 'ይግቡ',
    register: 'ይመዝገቡ',
    no_account: 'መለያ የሎትም?',
    has_account: 'ቀድሞውኑ መለያ አሎት?',
    demo_accounts: 'የሙከራ መለያዎች',

    // Catalog
    catalog_title: 'የመጻሕፍት ካታሎግ',
    search_books: 'መጻሕፍትን ይፈልጉ...',
    all_languages: 'ሁሉም ቋንቋዎች',
    english: 'እንግሊዝኛ',
    amharic: 'አማርኛ',
    no_books_found: 'ምንም መጻሕፍት አልተገኙም።',
    purchase: 'ይግዙ',
    read_now: 'አሁን ያንብቡ',
    purchased: 'ተገዝቷል ✓',
    birr: 'ብር',

    // Library
    my_library_title: 'የእኔ ቤተ-መጽሐፍት',
    my_books: 'የእኔ መጻሕፍት',
    recommendations: 'የሚመከሩ',
    no_books_yet: 'በቤተ-መጽሐፍትዎ ውስጥ እስካሁን ምንም መጻሕፍት የሉም።',
    browse_catalog_cta: 'የሚወዱትን መጽሐፍ ለማግኘት ካታሎጉን ያስሱ!',
    no_recommendations: 'እስካሁን ምንም የተሰጡ ምክሮች የሉም።',
    purchase_more: 'ለእርስዎ የተመረጡ መጻሕፍትን ለማየት ተጨማሪ መጻሕፍትን ይግዙ!',
    download_pdf: 'PDF ያውርዱ',

    // Publish
    publish_book: 'መጽሐፍ ያሳትሙ',
    book_title: 'የመጽሐፉ ርዕስ',
    description: 'ማብራሪያ',
    price_birr: 'ዋጋ (በብር)',
    language: 'ቋንቋ',
    cover_url: 'የሽፋን ምስል ማስፈንጠሪያ (URL)',
    pdf_url: 'የ PDF ማስፈንጠሪያ (URL)',
    publish_btn: 'መጽሐፍ ያሳትሙ',
    publishing: 'በማሳተም ላይ...',
    my_publications: 'የእኔ ህትመቶች',
    no_publications: 'እስካሁን ምንም መጻሕፍት አላሳተሙም።',

    // Revenue
    revenue_title: 'የገቢ ማጠቃለያ',
    total_revenue: 'ጠቅላላ ገቢ',
    total_sales: 'ጠቅላላ ሽያጭ',
    avg_price: 'አማካይ ዋጋ',
    recent_sales: 'የቅርብ ጊዜ ሽያጮች',
    no_sales: 'እስካሁን ምንም ሽያጭ የለም።',
    book: 'መጽሐፍ',
    buyer: 'ገዢ',
    amount: 'መጠን',
    date: 'ቀን',

    // Admin
    admin_panel: 'የአስተዳዳሪ ማዕከል',
    total_books: 'ጠቅላላ መጻሕፍት',
    total_users: 'ጠቅላላ ተጠቃሚዎች',
    total_purchases: 'ጠቅላላ ግዢዎች',
    manage_books: 'መጻሕፍትን ያስተዳድሩ',
    title_author: 'ርዕስ / ደራሲ',
    actions: 'ተግባራት',
    delete: 'ሰርዝ',

    // AI Assistant
    ai_assistant: 'የ AI ጽሑፍ ረዳት',
    ai_desc: 'የጽሑፍዎን ጥራት እና ማራኪነት ለማሻሻል በ AI የተደገፈ ግብረ-መልስ ያግኙ።',
    paste_text: 'ለትንተና ጽሑፍዎን እዚህ ያስገቡ፡',
    analyze: 'በ AI ይተንትኑ →',
    analyzing: 'በመተንተን ላይ...',
    ai_feedback: 'የ AI ግብረ-መልስ',
    suggestions: '💡 አስተያየቶች',
    submit_for_feedback: 'በ AI የተደገፈ ግብረ-መልስ ለማግኘት ጽሑፍዎን ያስገቡ',
    ai_analyzing: 'AI ጽሑፍዎን በመተንተን ላይ ነው...',

    // Payment
    purchase_book: 'መጽሐፍ ይግዙ',
    select_payment: 'የክፍያ አማራጭ ይምረጡ',
    phone_number: 'ስልክ ቁጥር / የባንክ ሂሳብ',
    pay_now: 'አሁን ይክፈሉ',
    processing: 'በማካሄድ ላይ...',
    payment_success: '✅ ክፍያዎ ተሳክቷል!',
    continue_reading: 'ማንበብዎን ይቀጥሉ',
    cancel: 'ይሰርዙ',

    // Missing Keys
    publish_subtitle: 'ስራዎን በመላው ዓለም ላሉ ኢትዮጵያውያን አንባቢዎች ያካፍሉ',
    library_subtitle: 'የገዟቸው መጻሕፍት — በመስመር ላይ ወይም በ GETSE መተግበሪያ ያንብቡ',
    purchased_on: 'የተገዛበት፡',
    view_in_catalog: 'በካታሎግ ውስጥ ይመልከቱ',
    revenue_subtitle: 'የመጽሐፍዎን ሽያጭ እና ገቢ ይከታተሉ',
    no_sales_yet: 'እስካሁን ምንም ሽያጭ የለም። መጻሕፍትን በማሳተም ገቢ ማግኘት ይጀምሩ!',
    sold: 'ተሽጧል',
    user_management: 'የተጠቃሚዎች አስተዳደር',
    refresh: '↻ አድስ',
    no_users_found: 'ምንም ተጠቃሚዎች አልተገኙም',
    remove: 'አስወግድ',
    ai_subtitle: 'በላቀ የ NLP ቴክኖሎጂ የተደገፈ — ለጽሑፍዎ ፈጣን ግብረ-መልስ፣ የቃላት ምርጫዎች እና የሽፋን ንድፍ ሀሳቦችን ያግኙ',
    analysis_type: 'የትንተና ዓይነት',
    oromia: 'ኦሮሚኛ',
    tigrinya: 'ትግርኛ',
    by: 'በ',
    login_to_purchase: 'ለመግዛት ይግቡ',
    patent_url: 'የባለቤትነት / የቅጂ መብት ሰነድ ዩአርኤል (PDF/ምስል)',
  }
}

export function t(lang, key) {
  return translations[lang]?.[key] ?? translations['en']?.[key] ?? key
}
